- hosts: localhost
  connection: local
  gather_facts: true
  become: false
  vars:
    OSPGUID: 5836  ### this value should be gotten from extra_vars
  tasks:
    - name: create ssh config for jumphost in tower
      copy:
        content: |
          Host workstation-{{ OSPGUID }}.rhpds.opentlc.com
           Hostname workstation-{{ OSPGUID }}.rhpds.opentlc.com
           IdentityFile ~/.ssh/openstack.pem
           ForwardAgent yes
           User cloud-user
           StrictHostKeyChecking no
           PasswordAuthentication no
          Host 10.10.10.*
           User cloud-user
           IdentityFile ~/.ssh/openstack.pem
           ProxyCommand ssh -F ./ssh.cfg cloud-user@workstation-{{ OSPGUID }}.rhpds.opentlc.com -W %h:%p -vvv
           StrictHostKeyChecking no
        dest: "./ssh.cfg"
#        dest: "/var/lib/awx/.ssh/config"
        mode: 0400
        owner: "{{ ansible_env.USER }}"
