- hosts: jumpbox
  gather_facts: false
  tasks:
    - name: Fetch Instance Info
      os_server_facts:
        cloud: ospcloud
        region_name: RegionOne
      register: result
    - name: Verify service
      uri:
        url: "http://{{ hostvars[ item ]['inventory_hostname']}}"
        return_content: yes
      with_items:
        - "{{ groups['frontends']}}"
      register: webpage
    - name: Fail if ANSIBLE is not in the page content
      fail:
      when: "'ANSIBLE' not in webpage.content"

