- hosts: jumpbox
  gather_facts: false
  tasks:
    - name: Fetch Instance Info
      os_server_facts:
        cloud: ospcloud
        region_name: RegionOne
      register: result
    - name: print groups
      debug:
        var: groups
    - name: Add host to
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.group }}"
      with_items: "{{result.ansible_facts.openstack_servers}}"
    - name: Verify service
      uri:
        url: "http://{{ hostvars[ item ]['inventory_hostname']}}"
        return_content: yes
      with_items:
        - "{{ groups['frontends']}}"
      register: webpage
#      until: webpage.status == "200"
#      retries: 2
#      delay: 5 
    - name: print webpage
      debug:
        var: webpage
    - name: print webpage content
      debug:
        var: webpage.results[0].content
    - name: Fail if host address is not in the page content
      fail:
      when: "'Ansible' not in webpage.results.content"
 #    when: "'200' not in webpage.results.status"

