- hosts: jumpbox
  gather_facts: false
  vars:
    the3tier_info:
        - { name: 'app1', group: 'apps' }
        - { name: 'app2', group: 'apps' }
        - { name: 'frontend', group: 'frontends' }
        - { name: 'appdb1', group: 'appdbs'}
    flavor_name: m2.small
    deployment: dev
  tasks:
  - name: print osp instances would be destroying
    debug:
      msg: "ops instance is sinking"
#  - name: Create a server instance
#    os_server:
#      cloud: ospcloud
#      name: "{{ item.name }}"
#      image: small-rhel
#      meta: "group={{ item.group }},deployment_name={{ deployment }}"
#      flavor: "{{ flavor_name }}"
#      security_groups: ICMP_and_SSH
#      key_name: ansible_ssh
#      nics:
#      - net-name: int_network
#      state: absent
#    with_items: "{{ the3tier_info }}"
