- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: create ssh config for jumphost in tower
      copy:
        content: |
          Host 10.10.10.*
           Hostname workstation-bcff.rhpds.opentlc.com
           IdentityFile ~/.ssh/openstack.pem
           ForwardAgent yes
           User cloud-user
           StrictHostKeyChecking no
           PasswordAuthentication no
          Host 10.10.10.*
           User cloud-user
           IdentityFile ~/.ssh/openstack.pem
           ProxyCommand ssh cloud-user@workstation-bcff.rhpds.opentlc.com -W %h:%p -vvv
           StrictHostKeyChecking no
        dest: "/var/lib/awx/.ssh/config"
        mode: 0400
          
    - name: where am i
      command: "ls -al"
#    - name: create ssh config for jumphost in tower
#      shell: 
#        cmd: |
#          cat <<EOF > ssh2.cfg
#          Host workstation-bcff.rhpds.opentlc.com
#           Hostname workstation-bcff.rhpds.opentlc.com
#           IdentityFile ~/.ssh/openstack.pem
#           ForwardAgent yes
#           User cloud-user
#           StrictHostKeyChecking no
#           PasswordAuthentication no
#          Host 10.10.10.*
#           User cloud-user
#           IdentityFile ~/.ssh/openstack.pem
#           ProxyCommand ssh -F ssh2.cfg cloud-user@workstation-bcff.rhpds.opentlc.com -W %h:%p -vvv
#           StrictHostKeyChecking no
#           EOF

- hosts: jumpbox
  gather_facts: false
  tasks:
    - name: Fetch Instance Info
      os_server_facts:
        cloud: ospcloud
        region_name: RegionOne
      register: result
    - name: Add host to
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.group }}"
      with_items: "{{result.ansible_facts.openstack_servers}}"
    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.deployment_name }}"
      with_items: "{{result.ansible_facts.openstack_servers}}"

- name: configuration
  hosts: appdbs:apps:frontends
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - common

- name: configure dbserver
  hosts: appdbs
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - dbserver

- name: configure wasserver and webserver
  hosts: apps
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - wasserver
    - webserver

- name: configure frontends
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - proxy
