- hosts: jumpbox
  gather_facts: false
  tasks:
   - name: Fetch Instance Info
     os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
     register: result
   - name: Add host to
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.group }}"
      fip: "{{ item.public_v4 }}"
      pip: "{{ item.private_v4 }}"
     with_items: "{{result.ansible_facts.openstack_servers}}"
   - name: Add host
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.deployment_name }}"
     with_items: "{{result.ansible_facts.openstack_servers}}"

- name: configuration
  hosts: appdb-group:apps-group:frontend-group
  #hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - common

- name: configure dbserver
  hosts: appdb_group
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - dbserver

- name: configure wasserver and webserver
  hosts: apps_group
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - wasserver
    - webserver

- name: configure frontends
  hosts: frontend_group
  gather_facts: false # remove later! speeds up testing
  become: true
  roles:
    - proxy
