- hosts: jumpbox
  gather_facts: false
  tasks:
   - name: Fetch Instance Info
     os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
     register: result
   - name: Add host to
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.group }}"
      fip: "{{ item.public_v4 }}"
      pip: "{{ item.private_v4 }}"
     with_items: "{{result.ansible_facts.openstack_servers}}"
   - name: Add host
     add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.deployment_name }}"
     with_items: "{{result.ansible_facts.openstack_servers}}"

- name: configuration
  hosts: appdbs:apps:frontends
  #hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true
  tasks:
    - include_role:
        name: common

- name: configure dbserver
  hosts: appdbs
  gather_facts: false # remove later! speeds up testing
  become: true
  tasks:
    - include_role:
        name: dbserver

- name: configure wasserver and webserver
  hosts: apps
  gather_facts: false # remove later! speeds up testing
  become: true
  tasks:
    - include_role:
        name: wasserver
      delegate_to: workstation-bcff.rhpds.opentlc.com
    - include_role:
        name: webserver

- name: configure frontends
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true
  tasks:
    - include_role:
        name: proxy
